Server:
  port: 8000
  forward-headers-strategy: framework

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      global-cors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - Authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - PUT
              - GET
              - POST
              - PATCH
              - DELETE
              - OPTIONS
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
        #              - JwtAuthenticationFilter
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1

        - id: host-service
          uri: lb://HOST-SERVICE
          predicates:
            - Path=/host-service/**
          filters:
            - StripPrefix=1

        - id: parking-service
          uri: lb://PARKING-SERVICE
          predicates:
            - Path=/parking-service/**
          filters:
            - StripPrefix=1

        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservation-service/**
          filters:
            - StripPrefix=1

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/**
          filters:
            - StripPrefix=1

        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review-service/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification-service/**
          filters:
            - StripPrefix=1

        - id: media-service
          uri: lb://MEDIA-SERVICE
          predicates:
            - Path=/media-service/**
          filters:
            - StripPrefix=1

        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/**
          filters:
            - StripPrefix=1
#              jwtfilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs  # API ?? ??
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

    urls:
      - url: "/feed-service/v3/api-docs"
        name: "Feed Service API"
      - url: "/auth-service/v3/api-docs"
        name: "Auth Service API"

